library("ggplot2")#Cargo libreria para graficar
library("scales")
library("GGally")
pdf("D:\\Dropbox\\Año 5\\WikiAnalisis\\R scripts\\Histogramas.pdf")
print(ggplot(df.big)+geom_histogram(aes(x=includeonly),binwidth = 3, fill="gray")+ggtitle("includeonly"))
print(ggplot(df.big)+geom_histogram(aes(x=big),binwidth = 3, fill="gray")+ggtitle("big"))
print(ggplot(df.big)+geom_histogram(aes(x=cite),binwidth = 3, fill="gray")+ggtitle("cite"))
print(ggplot(df.big)+geom_histogram(aes(x=infobox),binwidth = 1, fill="gray")+ggtitle("infobox"))
print(ggplot(df.big)+geom_histogram(aes(x=italic),binwidth = 3, fill="gray")+ggtitle("italic"))
print(ggplot(df.big)+geom_histogram(aes(x=heading2),binwidth = 3, fill="gray")+ggtitle("heading2"))
print(ggplot(df.big)+geom_histogram(aes(x=blod),binwidth = 3, fill="gray")+ggtitle("blod"))
print(ggplot(df.big)+geom_histogram(aes(x=sup),binwidth = 3, fill="gray")+ggtitle("sup"))
print(ggplot(df.big)+geom_histogram(aes(x=file),binwidth = 3, fill="gray")+ggtitle("file"))
print(ggplot(df.big)+geom_histogram(aes(x=indent1),binwidth = 5, fill="gray")+ggtitle("indent1"))
print(ggplot(df.big)+geom_histogram(aes(x=sub),binwidth = 3, fill="gray")+ggtitle("sub"))
print(ggplot(df.big)+geom_histogram(aes(x=heading5),binwidth = 1, fill="gray")+ggtitle("heading5"))
print(ggplot(df.big)+geom_histogram(aes(x=none),binwidth = 3, fill="gray")+ggtitle("none"))
print(ggplot(df.big)+geom_histogram(aes(x=blockquote),binwidth = 3, fill="gray")+ggtitle("blockquote"))
print(ggplot(df.big)+geom_histogram(aes(x=bulletedelement),binwidth = 3, fill="gray")+ggtitle("bulletedelement"))
print(ggplot(df.big)+geom_histogram(aes(x=wikitable),binwidth = 1, fill="gray")+ggtitle("wikitable"))
print(ggplot(df.big)+geom_histogram(aes(x=heading3),binwidth = 3, fill="gray")+ggtitle("heading3"))
print(ggplot(df.big)+geom_histogram(aes(x=nowiki),binwidth = 3, fill="gray")+ggtitle("nowiki"))
print(ggplot(df.big)+geom_histogram(aes(x=internal),binwidth = 5, fill="gray")+ggtitle("internal"))
print(ggplot(df.big)+geom_histogram(aes(x=italicblod),binwidth = 3, fill="gray")+ggtitle("italicblod"))
print(ggplot(df.big)+geom_histogram(aes(x=external),binwidth = 3, fill="gray")+ggtitle("external"))
print(ggplot(df.big)+geom_histogram(aes(x=reference),binwidth = 3, fill="gray")+ggtitle("reference"))
print(ggplot(df.big)+geom_histogram(aes(x=numberedelement),binwidth = 3, fill="gray")+ggtitle("numberedelement"))
print(ggplot(df.big)+geom_histogram(aes(x=indent2),binwidth = 3, fill="gray")+ggtitle("indent2"))
print(ggplot(df.big)+geom_histogram(aes(x=s ),binwidth = 3, fill="gray")+ggtitle("s "))
print(ggplot(df.big)+geom_histogram(aes(x=heading4),binwidth = 3, fill="gray")+ggtitle("heading4"))
print(ggplot(df.big)+geom_histogram(aes(x=redirection),binwidth = 3, fill="gray")+ggtitle("redirection"))
print(ggplot(df.big)+geom_histogram(aes(x=small),binwidth = 3, fill="gray")+ggtitle("small"))
#print(ggplot(df.big)+geom_histogram(aes(x=content_size),binwidth = 3, fill="gray")+ggtitle("content_size"))
print(ggplot(df.big)+geom_histogram(aes(x=date),binwidth = 3, fill="gray")+ggtitle("date"))
print(ggplot(df.big)+geom_histogram(aes(x=categories),binwidth = 1, fill="gray")+ggtitle("categories"))
print(ggplot(df.big)+geom_histogram(aes(x=pagename),binwidth = 3, fill="gray")+ggtitle("pagename"))
dev.off()
#---------------------------------------------------------------------------------------------------------
pdf("D:\\Dropbox\\Año 5\\WikiAnalisis\\R scripts\\Densidad.pdf")
print(ggplot(df.big)+geom_density(aes(x=includeonly))+scale_x_continuous()+ggtitle("includeonly"))
print(ggplot(df.big)+geom_density(aes(x=big))+scale_x_continuous( )+ggtitle("big"))
print(ggplot(df.big)+geom_density(aes(x=cite))+scale_x_continuous( )+ggtitle("cite"))
print(ggplot(df.big)+geom_density(aes(x=infobox))+scale_x_continuous( )+ggtitle("infobox"))
print(ggplot(df.big)+geom_density(aes(x=italic))+scale_x_continuous( )+ggtitle("italic"))
print(ggplot(df.big)+geom_density(aes(x=heading2))+scale_x_continuous( )+ggtitle("heading2"))
print(ggplot(df.big)+geom_density(aes(x=blod))+scale_x_continuous( )+ggtitle("blod"))
print(ggplot(df.big)+geom_density(aes(x=sup))+scale_x_continuous( )+ggtitle("sup"))
print(ggplot(df.big)+geom_density(aes(x=file))+scale_x_continuous( )+ggtitle("file"))
print(ggplot(df.big)+geom_density(aes(x=indent1))+scale_x_continuous( )+ggtitle("indent1"))
print(ggplot(df.big)+geom_density(aes(x=sub))+scale_x_continuous( )+ggtitle("sub"))
print(ggplot(df.big)+geom_density(aes(x=heading5))+scale_x_continuous( )+ggtitle("heading5"))
print(ggplot(df.big)+geom_density(aes(x=none))+scale_x_continuous( )+ggtitle("none"))
print(ggplot(df.big)+geom_density(aes(x=blockquote))+scale_x_continuous( )+ggtitle("blockquote"))
print(ggplot(df.big)+geom_density(aes(x=bulletedelement))+scale_x_continuous( )+ggtitle("bulletedelement"))
print(ggplot(df.big)+geom_density(aes(x=wikitable))+scale_x_continuous( )+ggtitle("wikitable"))
print(ggplot(df.big)+geom_density(aes(x=heading3))+scale_x_continuous( )+ggtitle("heading3"))
print(ggplot(df.big)+geom_density(aes(x=nowiki))+scale_x_continuous( )+ggtitle("nowiki"))
print(ggplot(df.big)+geom_density(aes(x=internal))+scale_x_continuous( )+ggtitle("internal"))
print(ggplot(df.big)+geom_density(aes(x=italicblod))+scale_x_continuous( )+ggtitle("italicblod"))
print(ggplot(df.big)+geom_density(aes(x=external))+scale_x_continuous( )+ggtitle("external"))
print(ggplot(df.big)+geom_density(aes(x=reference))+scale_x_continuous( )+ggtitle("reference"))
print(ggplot(df.big)+geom_density(aes(x=numberedelement))+scale_x_continuous( )+ggtitle("numberedelement"))
print(ggplot(df.big)+geom_density(aes(x=indent2))+scale_x_continuous( )+ggtitle("indent2"))
print(ggplot(df.big)+geom_density(aes(x=s ))+scale_x_continuous( )+ggtitle("s "))
print(ggplot(df.big)+geom_density(aes(x=heading4))+scale_x_continuous( )+ggtitle("heading4"))
print(ggplot(df.big)+geom_density(aes(x=redirection))+scale_x_continuous( )+ggtitle("redirection"))
print(ggplot(df.big)+geom_density(aes(x=small))+scale_x_continuous( )+ggtitle("small"))
print(ggplot(df.big)+geom_density(aes(x=content_size))+scale_x_continuous( )+ggtitle("content_size"))
print(ggplot(df.big)+geom_density(aes(x=date))+scale_x_date( )+ggtitle("date"))
print(ggplot(df.big)+geom_density(aes(x=categories))+scale_x_continuous( )+ggtitle("categories"))
print(ggplot(df.big)+geom_density(aes(x=pagename))+scale_x_continuous( )+ggtitle("pagename"))
dev.off()
#---------------------------------------------------------------------------------------------------------
pdf("D:\\Dropbox\\Año 5\\WikiAnalisis\\R scripts\\DensidadLogaritmica.pdf")
print(ggplot(df.big)+geom_density(aes(x=includeonly))+scale_x_log10()+ggtitle("includeonly"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=big))+scale_x_log10( )+ggtitle("big"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=cite))+scale_x_log10( )+ggtitle("cite"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=infobox))+ scale_x_log10( )+ggtitle("infobox"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=italic))+ scale_x_log10( )+ggtitle("italic"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=heading2))+ scale_x_log10( )+ggtitle("heading2"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=blod))+ scale_x_log10( )+ggtitle("blod"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=sup))+ scale_x_log10( )+ggtitle("sup"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=file))+ scale_x_log10( )+ggtitle("file"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=indent1))+ scale_x_log10( )+ggtitle("indent1"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=sub))+ scale_x_log10( )+ggtitle("sub"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=heading5))+ scale_x_log10( )+ggtitle("heading5"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=none))+ scale_x_log10( )+ggtitle("none"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=blockquote))+ scale_x_log10( )+ggtitle("blockquote"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=bulletedelement))+ scale_x_log10( )+ggtitle("bulletedelement"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=wikitable))+ scale_x_log10( )+ggtitle("wikitable"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=heading3))+ scale_x_log10( )+ggtitle("heading3"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=nowiki))+ scale_x_log10( )+ggtitle("nowiki"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=internal))+ scale_x_log10( )+ggtitle("internal"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=italicblod))+ scale_x_log10( )+ggtitle("italicblod"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=external))+ scale_x_log10( )+ggtitle("external"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=reference))+ scale_x_log10( )+ggtitle("reference"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=numberedelement))+ scale_x_log10( )+ggtitle("numberedelement"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=indent2))+ scale_x_log10( )+ggtitle("indent2"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=s ))+ scale_x_log10( )+ggtitle("s "))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=heading4))+ scale_x_log10( )+ggtitle("heading4"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=redirection))+ scale_x_log10( )+ggtitle("redirection"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=small))+ scale_x_log10( )+ggtitle("small"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=content_size))+ scale_x_log10( )+ggtitle("content_size"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=date))+scale_x_date( )+ggtitle("date"))
print(ggplot(df.big)+geom_density(aes(x=categories))+ scale_x_log10( )+ggtitle("categories"))+annotation_logticks(sides="bt")
print(ggplot(df.big)+geom_density(aes(x=pagename))+ scale_x_log10( )+ggtitle("pagename"))+annotation_logticks(sides="bt")
dev.off()
#---------------------------------------------------------------------------------------------------------
my_fn <- function(data, mapping, method="loess", ...){
  p <- ggplot(data = data, mapping = mapping) + 
    geom_point() + 
    geom_smooth(method=method, ...)
  p
}
ggpairs(df.big, 
        lower = list(continuous = my_fn),
        title = "Pares de Variables",  
        axisLabels = "show")